Add function to dynamically turn specific errors into HTTPErrorResponse.
fi-ts/cloud-go pull request #21
Opened 2020-10-15 09:36 UTC by Gerrit91

2020-10-15 09:48 UTC, majst01 requested changes
I think a test for the new exported function should be implemented

2020-10-15 10:14 UTC, Gerrit91 commented
Added a test, also for https://github.com/metal-stack/metal-go/pull/44.

2020-10-26 08:34 UTC, majst01 commented
needs metal-go update

2020-10-27 13:46 UTC, majst01 approved these changes

2020-10-27 13:46 UTC, merged